name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Используем сервер на базе Linux для сборки

    steps:
      # Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Устанавливаем JDK для сборки
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Устанавливаем Android SDK
      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      # Собираем APK с помощью Gradle
      - name: Build APK
        run: ./gradlew assembleDebug

      # Сохраняем APK как артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
